version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    depends_on:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
  php:
    build: ./docker/php-fpm/.
    working_dir: /app
    depends_on:
      - click_server
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
  click_server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - clickhouse:/var/lib/clickhouse

volumes:
  clickhouse: